name: tizen_native
description: A new flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  ffi: ^1.1.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      tizen:
        pluginClass: TizenNativePlugin
        fileName: tizen_native_plugin.h
